
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lybvbkfagawmwsemibhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YnZia2ZhZ2F3bXdzZW1pYmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjQyMjksImV4cCI6MjA2MzQwMDIyOX0.nVOtxHT23xWV6zuC-ffClqMwcaPHeLiA4QqyrEr8aEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
